from __future__ import annotations

from neodym_lead_discovery.enrichment.website import enrich_public_website
from neodym_lead_discovery.models import LeadCandidate, WebsitePageProfile

HOME_HTML = """
<html><head><title>ABC Logistics</title>
<meta name="description" content="Freight operations partner."></head>
<body>
  <h1>Freight operations</h1>
  <p>Dispatch workflow and customer support coordination.</p>
  <a href="/about">About</a>
  <a href="/services">Services</a>
  <a href="/team">Team</a>
  <a href="/contact">Contact</a>
  <a href="/blog/random">Blog</a>
</body></html>
"""

ABOUT_HTML = """
<html><body>
  <h1>About ABC</h1>
  <p>We run document processing and compliance intake for regional shippers.</p>
</body></html>
"""

SERVICES_HTML = """
<html><body>
  <h1>Services</h1>
  <h2>Claims intake</h2>
  <p>Claims, scheduling, warehouse coordination, and workflow automation support.</p>
</body></html>
"""

TEAM_HTML = """
<html><body>
  <h1>Team</h1>
  <p>Jane Miller - Head of Operations - jane@example.com</p>
</body></html>
"""

CONTACT_HTML = """
<html><body>
  <h1>Contact us</h1>
  <p>Email operations@example.com for support and intake requests.</p>
</body></html>
"""


def page_analyzer(candidate: LeadCandidate, profile: WebsitePageProfile) -> dict[str, object]:
    return {
        "page_summary": f"{candidate.company_name} page covering {profile.page_type} content.",
        "manual_process_signals": profile.operational_signals,
        "automation_opportunities": [
            f"Potential automation around {signal}." for signal in profile.operational_signals
        ],
        "supporting_excerpt": profile.text[:500],
        "limitations": ["Generated by deterministic test analyzer."],
    }


def test_enrich_public_website_crawls_relevant_pages_and_builds_llm_profile():
    pages = {
        "https://abclogistics.example": HOME_HTML,
        "https://abclogistics.example/about": ABOUT_HTML,
        "https://abclogistics.example/services": SERVICES_HTML,
        "https://abclogistics.example/team": TEAM_HTML,
        "https://abclogistics.example/contact": CONTACT_HTML,
    }
    fetched_urls: list[str] = []

    def fetcher(url: str) -> str:
        fetched_urls.append(url)
        return pages[url]

    candidate = LeadCandidate(
        company_name="ABC Logistics",
        website="https://abclogistics.example",
        source_links=["https://abclogistics.example"],
    )

    enriched = enrich_public_website(
        candidate,
        fetcher=fetcher,
        page_evidence_analyzer=page_analyzer,
        max_pages=5,
    )

    assert fetched_urls == [
        "https://abclogistics.example",
        "https://abclogistics.example/about",
        "https://abclogistics.example/services",
        "https://abclogistics.example/team",
        "https://abclogistics.example/contact",
    ]
    assert "https://abclogistics.example/blog/random" not in enriched.candidate.source_links
    assert len(enriched.page_profiles) == 5
    assert enriched.structured_profile is not None
    assert enriched.structured_profile.company_name == "ABC Logistics"
    assert "Freight operations partner." in enriched.structured_profile.summary
    assert "Claims intake" in enriched.structured_profile.services_or_products
    assert "claims" in enriched.structured_profile.operational_complexity_signals
    assert "document_processing" in enriched.structured_profile.operational_complexity_signals
    assert enriched.contact_candidates[0].email == "jane@example.com"
    assert enriched.structured_profile.llm_context["pages_crawled"] == 5
    assert "page_evidence" in enriched.structured_profile.llm_context
    assert "page_summaries" not in enriched.structured_profile.llm_context
    page_evidence = enriched.structured_profile.llm_context["page_evidence"]
    assert isinstance(page_evidence, list)
    assert page_evidence[0]["url"] == "https://abclogistics.example"
    assert page_evidence[0]["page_summary"] == "ABC Logistics page covering home content."
    assert "text_excerpt" not in page_evidence[0]
    assert "Claims, scheduling" in enriched.structured_profile.llm_context["evidence_text"]


def test_enrich_public_website_uses_javascript_renderer_when_static_html_has_no_meaningful_text():
    static_html = '<html><body><div id="root"></div><script src="/app.js"></script></body></html>'
    rendered_html = """
    <html><head><title>Rendered Co</title></head><body>
      <h1>Rendered services</h1><p>Support workflow and claims intake platform.</p>
    </body></html>
    """

    def fetcher(url: str) -> str:
        assert url == "https://rendered.example"
        return static_html

    def renderer(url: str) -> str:
        assert url == "https://rendered.example"
        return rendered_html

    candidate = LeadCandidate(company_name="Rendered Co", website="https://rendered.example")

    enriched = enrich_public_website(
        candidate,
        fetcher=fetcher,
        javascript_renderer=renderer,
        page_evidence_analyzer=page_analyzer,
    )

    assert enriched.page_profiles[0].rendered_with_javascript is True
    assert enriched.website_title == "Rendered Co"
    assert "claims" in enriched.operational_complexity_signals
